name: md_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  # gromacs se omite aqui: usar imagen Docker nvcr.io/hpc/gromacs:2024.1
  # que incluye GROMACS compilado con soporte CUDA/GPU completo
  - acpype
  - openbabel
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - ipykernel
  - pip
